### ISSUE TITLE
unable to draw image

### ISSUE THREAD

**Issue by improvisor40** [jonegil/gui-with-gio#44]
i know there's probably gonna be some bugs here and there, but i'm on a a verge to get an idea of mine into reality with golang, but i'm being restricted by the fact that i'm no getting the docs/examples to work, i feel like they are outdated and will only work with old versions , i couldn't get images to display, here's my code and bug report:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x666d80]

goroutine 19 [running]:
gioui.org/op/paint.NewImageOp({0x0, 0x0})
	/home/david/go/pkg/mod/gioui.org@v0.7.1/op/paint/paint.go:88 +0x1a0
main.Assemble(0xc000112008)
	/home/david/projects/TileAlign/gfx.go:58 +0x2ca
main.main.func1()
	/home/david/projects/TileAlign/gfx.go:35 +0x1f
created by main.main in goroutine 1
	/home/david/projects/TileAlign/gfx.go:33 +0x1a
exit status 2

```
````
func Assemble(window *app.Window) error {
	theme := material.NewTheme()
	var ops op.Ops
	for {
		switch e := window.Event().(type) {
		case app.DestroyEvent:
			return e.Err
		case app.FrameEvent:
			// This graphics context is used for managing the rendering state.
			gtx := app.NewContext(&ops, e)

			// Define an large label with an appropriate text:
			title := material.H1(theme, "Hello, Wrld")
			//new image
			img, _ := getImageFromFilePath("container.webp")
			imageOp := paint.NewImageOp(img)
			imageOp.Filter = paint.FilterNearest
			imageOp.Add(&ops)
			op.Affine(f32.Affine2D{}.Scale(f32.Pt(0, 0), f32.Pt(4, 4))).Add(&ops)
			paint.PaintOp{}.Add(&ops)
			// Change the color of the label.
			maroon := color.NRGBA{R: 127, G: 0, B: 0, A: 255}
			title.Color = maroon

			// Change the position of the label.
			title.Alignment = text.Middle

			// Draw the label to the graphics context.
			title.Layout(gtx)

			// Pass the drawing operations to the GPU.
			e.Frame(gtx.Ops)
		}
	}
}
````

**Comment by improvisor40** [comment]
this is from the official site, all i did was put it together to get an image to display, for the webp image i'm using this package: `golang.org/x/image/webp`

**Comment by jonegil** [comment]
Hi man. 

Great that you work with Gio. Unfortunately this repo is not an official doc, just my best effort to help and support the community. Have you tried the mailing list?

As this is a genral question, I'll close your issue though.
